package com.firmavanilla.block;

import com.firmavanilla.FirmaVanilla;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

/**
 * Decorative "tiles" blocks (vanilla deepslate-tiles style) in each of TFC's rock types — a form TFC doesn't
 * ship. Per rock: {@code firmavanilla:tiles/<rock>} (plain) and {@code .../cracked_tiles/<rock>} (cracked,
 * creative-only), plus the full vanilla shape family off the plain tiles — {@code tile_stairs/}, {@code tile_slab/}
 * and {@code tile_wall/<rock>}. All `Properties.copy(Blocks.STONE_BRICKS)`.
 *
 * <p>The textures are machine-generated by the CLUT pipeline: vanilla {@code deepslate_tiles} /
 * {@code cracked_deepslate_tiles} tile patterns recoloured (luminance-normalized palette remap) through each
 * rock's {@code tfc:rock/bricks/<rock>} or {@code .../smooth} palette (tools/generate-textures). The stairs/slab/
 * wall reuse the plain tile texture, so they add no images — only JSON. Proof-of-concept: no substitution wiring yet.
 */
public final class TileBlocks
{
    private TileBlocks() {}

    /** TFC's 20 rock types (matches {@code tfc:rock/bricks/<rock>}). */
    public static final List<String> ROCKS = List.of(
            "andesite", "basalt", "chalk", "chert", "claystone", "conglomerate", "dacite", "diorite", "dolomite", "gabbro",
            "gneiss", "granite", "limestone", "marble", "phyllite", "quartzite", "rhyolite", "schist", "shale", "slate");

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, FirmaVanilla.MODID);
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, FirmaVanilla.MODID);

    /** Plain tiles block per rock, in {@link #ROCKS} order (drives the creative tab). */
    public static final List<RegistryObject<Block>> ALL = new ArrayList<>();
    /** Cracked tiles block per rock (vanilla {@code cracked_deepslate_tiles} style), {@link #ROCKS} order. */
    public static final List<RegistryObject<Block>> CRACKED = new ArrayList<>();
    /** Tile stairs / slab / wall per rock, {@link #ROCKS} order. */
    public static final List<RegistryObject<Block>> STAIRS = new ArrayList<>();
    public static final List<RegistryObject<Block>> SLABS = new ArrayList<>();
    public static final List<RegistryObject<Block>> WALLS = new ArrayList<>();

    static
    {
        for (final String rock : ROCKS)
        {
            final RegistryObject<Block> base = register("tiles/" + rock, () -> new Block(props()));
            ALL.add(base);
            CRACKED.add(register("cracked_tiles/" + rock, () -> new Block(props())));
            // Forge's Supplier ctor — base block isn't built yet at registration time.
            STAIRS.add(register("tile_stairs/" + rock, () -> new StairBlock(() -> base.get().defaultBlockState(), props())));
            SLABS.add(register("tile_slab/" + rock, () -> new SlabBlock(props())));
            WALLS.add(register("tile_wall/" + rock, () -> new WallBlock(props())));
        }
    }

    private static BlockBehaviour.Properties props()
    {
        return BlockBehaviour.Properties.copy(Blocks.STONE_BRICKS);
    }

    private static RegistryObject<Block> register(final String name, final Supplier<Block> sup)
    {
        final RegistryObject<Block> block = BLOCKS.register(name, sup);
        ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
        return block;
    }

    public static void init(final IEventBus modBus)
    {
        BLOCKS.register(modBus);
        ITEMS.register(modBus);
    }
}
