package com.firmavanilla.block;

import com.firmavanilla.FirmaVanilla;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * A <b>block of beeswax</b> ({@code firmavanilla:beeswax_block}) — the vanilla honeycomb-block motif recoloured
 * to FirmaLife beeswax's warm-tan palette (CLUT, generated by {@code beeswax.cs}). A plain decorative full cube
 * with vanilla honeycomb-block properties (sound/hardness, no tool needed), the beeswax analogue of vanilla's
 * 4-honeycomb → honeycomb-block.
 *
 * <p>The block itself carries <b>no FirmaLife dependency</b> (firmavanilla is TFC-only, and the texture ships as a
 * committed derivative): only its crafting recipe consumes {@code firmalife:beeswax}, and that recipe is gated by
 * a {@code forge:mod_loaded} condition so it simply doesn't load when FirmaLife is absent.
 */
public final class WaxBlocks
{
    private WaxBlocks() {}

    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, FirmaVanilla.MODID);
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, FirmaVanilla.MODID);

    public static final RegistryObject<Block> BEESWAX_BLOCK = BLOCKS.register("beeswax_block",
            () -> new Block(BlockBehaviour.Properties.copy(Blocks.HONEYCOMB_BLOCK)));

    static
    {
        ITEMS.register("beeswax_block", () -> new BlockItem(BEESWAX_BLOCK.get(), new Item.Properties()));
    }

    public static void init(final IEventBus modBus)
    {
        BLOCKS.register(modBus);
        ITEMS.register(modBus);
    }
}
